trigger:
- dev
- master
- release/*

variables:
  - group: expo-variables

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    cd ReactNativeCore
    npm install
    npm install eas-cli
    npx eas-cli build --platform all --non-interactive
  displayName: 'Install dependencies and push build to Expo'