# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev
- master
- release/*

variables:
  - group: expo-variables

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    npm install -g eas-cli
    cd ReactNativeCore
    npm install
  displayName: 'Installing dependencies'

- script: |
    cd ReactNativeCore
    npx eas-cli build --platform all --non-interactive
  displayName: 'Building using EAS CLI'
