trigger:
- dev
- master
- release/*

variables:
  - group: expo-variables

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    cd ReactNativeCore
    npm install
  displayName: 'Installing dependencies'

- script: |
    cd ReactNativeCore
    npm install eas-cli
  displayName: 'Installing EAS command line interface'

- script: |
    cd ReactNativeCore
    npx eas-cli build --platform all --non-interactive
  displayName: 'Pushing build to Expo servers'


